# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

data = {
  users: [
    {username: "blair", email: "blair81@gmail.com", password: "password", password_confirmation: "password", bio: "Rails hacker", full_name: "Blair Anderson"}
  ],
  boards: [
    {slug: :jobs, name: "Jobs", description: "Find a new job with intent. be organized and mindful. "},
    {slug: :life, name: "Life", description: "SelfHelp is real. You must treat yo' self to the good life. "},
    {slug: :ideas, name: "Ideas", description: "literally just straight up Board for ideas and projects and hobbies"}
  ],
  lists: [
    {board: :life, slug: :movement, position: 1, title: "Join Some Movements", description: "For Joining Movements", open: true},
    {board: :life, slug: :friends, position: 2, title: "Make Some Friends", description: "For helping organize friendship contacts and updates", open: true},
    {board: :life, slug: :health, position: 3, title: "Get Health", description: "for organizing health related things", open: true},
    {board: :life, slug: :active, position: 4, title: "Get Active", description: "Get Active", open: true},
    {board: :jobs, slug: :research, position: 1, title: "Research", description: "meta-kanban for this kanban app", open: true},
    {board: :jobs, slug: :applied, position: 2, title: "Applied", description: "my second app academy app", open: true},
    {board: :jobs, slug: :interviewing, position: 3, title: "Interviewing", description: "job search board", open: true, },
    {board: :jobs, slug: :offers, position: 4, title: "Offers", description: "Chores manager for Simpson family", open: true, },
    {board: :jobs, slug: :rejected, position: 5, title: "Rejected", description: "List of companies that are rejected.", open: true}
  ]
}
User.destroy_all
Board.destroy_all
BoardMember.destroy_all
List.destroy_all
Card.destroy_all
User.create(data[:users])
User.all.each do |u|
  puts "user: #{u.attributes}"
end

Board.create(data[:boards])
Board.all.each { |b| puts "board: #{b.attributes}" }

User.find_each do |user|
  bms = Board.select("id as board_id").map do |board|
    attrs = board.attributes
    attrs[:member_id] = user.id
    attrs[:admin] = true
    attrs
  end
  BoardMember.create(bms)
end

data[:lists].map do |list|
  board = Board.where(slug: list.delete(:board)).first
  if board
    list[:board_id] = board.id
    list = List.create(list)
    puts "list: #{list.attributes}"
  end
end


trello = JSON.parse(File.read("db/cards.json"))

list = trello["lists"].find { |f| f["name"] == "Research" }

cards = trello["cards"].select do |c|
  c["idList"] == list["id"]
end

research = List.where(slug: :research).first
if research
  cards.each do |card|
    company, title = card['name'].split(" - ")
    card = research.cards.create({
        assignee_id: 1,
        title: title,
        company: company,
        url: card['desc']
      })
    puts "card: #{card.attributes}"
  end
end
